
// International testimonial data
export const testimonials = [
  // French testimonials
  {
    id: 1,
    name: "Bruno Montier",
    company: "AGRO FOOD INDUSTRIE MARRAKECH",
    position: "Fondateur Directeur Général",
    quote: "Dominiqk a transformé notre présence en ligne avec une stratégie de marketing digital exceptionnelle. Grâce à son expertise, notre nouvelle gamme de produits a connu un succès immédiat sur le marché international.",
    image: "/lovable-uploads/3b1bf266-238b-4dd4-8ef8-13cec30e562e.png",
    country: "France",
    language: "French",
    rating: 5,
  },
  {
    id: 2,
    name: "Sophie Moreau",
    company: "Digital Innovation Group",
    position: "Chief Technology Officer",
    quote: "Le travail de Dominiqk sur notre plateforme a révolutionné notre approche. Sa maîtrise des technologies de pointe a fait de notre solution un modèle dans notre secteur.",
    image: "/lovable-uploads/62e7c5f4-476c-4ca6-80b8-75e9973ecfa4.png",
    country: "Canada",
    language: "French",
    rating: 5,
  },
  {
    id: 3,
    name: "François Lambert",
    company: "PUBLI TICKET MAROC",
    position: "CEO",
    quote: "Notre collaboration avec Dominiqk a été un véritable tournant pour Publi Ticket. Sa vision novatrice et sa compréhension approfondie du marché digital nous ont permis de nous démarquer considérablement.",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
    country: "Belgium",
    language: "French",
    rating: 5,
  },
  {
    id: 4,
    name: "Amélie Lefèvre",
    company: "Tech Solutions Paris",
    position: "Responsable Innovation",
    quote: "Dominiqk a su apporter des solutions sur mesure pour notre transition digitale. Son approche holistique et sa compréhension des enjeux ont fait toute la différence. Je recommande vivement ses services à toute entreprise cherchant à innover.",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    country: "France",
    language: "French",
    rating: 5,
  },
  {
    id: 5,
    name: "Jean-Marc Bissieux",
    company: "Fintech Solutions Paris",
    position: "Directeur Technologique",
    quote: "L'expertise de Dominiqk en intelligence artificielle nous a permis d'optimiser considérablement nos systèmes d'analyse financière. Un professionnel d'exception avec une vision claire de l'avenir technologique.",
    image: "https://randomuser.me/api/portraits/men/33.jpg",
    country: "France",
    language: "French",
    rating: 5,
  },
  {
    id: 6,
    name: "Claire Dubourg",
    company: "Alliance Numérique International",
    position: "Présidente",
    quote: "Dominiqk a orchestré notre transformation numérique avec brio. Son expertise en IA a permis à notre consortium de devenir un leader dans notre domaine en moins d'un an.",
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    country: "Switzerland",
    language: "French",
    rating: 5,
  },
  // English testimonials
  {
    id: 7,
    name: "Michael Richardson",
    company: "Global Tech Solutions",
    position: "CEO",
    quote: "Dominiqk's approach to digital transformation is truly revolutionary. His deep understanding of AI technologies and their practical applications helped us streamline our operations and increase revenue by 40% in just six months.",
    image: "https://randomuser.me/api/portraits/men/45.jpg",
    country: "United Kingdom",
    language: "English",
    rating: 5,
  },
  {
    id: 8,
    name: "Sarah Johnson",
    company: "TechVentures International",
    position: "Innovation Director",
    quote: "Working with Dominiqk was a game-changer for our startup ecosystem. His insights into emerging technologies and market trends provided us with a roadmap that attracted significant investment and international partnerships.",
    image: "https://randomuser.me/api/portraits/women/48.jpg",
    country: "United States",
    language: "English",
    rating: 5,
  },
  {
    id: 9,
    name: "David Miller",
    company: "London Digital Academy",
    position: "Managing Director",
    quote: "Dominiqk delivered an exceptional training program for our executives on AI implementation strategies. His practical approach and vast experience across different markets made the content immediately applicable to our diverse client base.",
    image: "https://randomuser.me/api/portraits/men/41.jpg",
    country: "United Kingdom",
    language: "English",
    rating: 5,
  },
  {
    id: 10,
    name: "Elizabeth Taylor",
    company: "Digital Development Coalition",
    position: "Project Lead",
    quote: "Dominiqk's contribution to our digital governance project was invaluable. He successfully bridged technical expertise with business needs, resulting in a solution that was readily adopted across our organization.",
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    country: "Australia",
    language: "English",
    rating: 5,
  },
  {
    id: 11,
    name: "James Wilson",
    company: "Tech Partners International",
    position: "Strategy Officer",
    quote: "Dominiqk's expertise in multiple markets makes him an invaluable consultant. His strategic guidance helped us navigate complex regulatory environments and establish successful digital partnerships across different countries.",
    image: "https://randomuser.me/api/portraits/men/37.jpg",
    country: "United States",
    language: "English",
    rating: 5,
  },
  {
    id: 12,
    name: "Victoria Adams",
    company: "Global AI Solutions",
    position: "Head of Innovation",
    quote: "Dominiqk's deep understanding of AI implementation in diverse markets helped us develop algorithms that outperformed our previous models by 60%. His expertise is truly global in scope.",
    image: "https://randomuser.me/api/portraits/women/35.jpg",
    country: "Canada",
    language: "English",
    rating: 5,
  },
  {
    id: 13,
    name: "Robert Brown",
    company: "Trans-Continental Investments",
    position: "Digital Assets Director",
    quote: "We engaged Dominiqk to evaluate digital opportunities across emerging markets. His insights were spot-on and led to several successful ventures that continue to yield impressive returns for our portfolio.",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    country: "Australia",
    language: "English",
    rating: 5,
  },
  // Spanish testimonials
  {
    id: 14,
    name: "Carlos Rodríguez",
    company: "Innovación Digital Madrid",
    position: "Director Ejecutivo",
    quote: "La colaboración con Dominiqk ha sido transformadora para nuestra empresa. Su enfoque estratégico en inteligencia artificial nos permitió expandirnos exitosamente en Europa y América.",
    image: "https://randomuser.me/api/portraits/men/55.jpg",
    country: "Spain",
    language: "Spanish",
    rating: 5,
  },
  {
    id: 15,
    name: "María González",
    company: "Tecnología Sin Fronteras",
    position: "Directora de Proyectos",
    quote: "Dominiqk aportó una perspectiva única a nuestros proyectos internacionales. Su habilidad para adaptar soluciones tecnológicas a diferentes contextos culturales fue clave para nuestro éxito.",
    image: "https://randomuser.me/api/portraits/women/58.jpg",
    country: "Mexico",
    language: "Spanish",
    rating: 5,
  },
  {
    id: 16,
    name: "Javier López",
    company: "Consultoría Digital Barcelona",
    position: "Jefe de Estrategia",
    quote: "La capacidad de Dominiqk para integrar soluciones de IA en entornos empresariales tradicionales es extraordinaria. Transformó completamente nuestra forma de interactuar con los clientes y optimizar procesos comerciales.",
    image: "https://randomuser.me/api/portraits/men/62.jpg",
    country: "Spain",
    language: "Spanish",
    rating: 5,
  },
  {
    id: 17,
    name: "Ana Martínez",
    company: "Futuro Digital Internacional",
    position: "Directora de Innovación",
    quote: "El conocimiento de Dominiqk sobre mercados y tecnologías disruptivas nos proporcionó una ventaja competitiva significativa. Su enfoque práctico y orientado a resultados generó impactos inmediatos en nuestro negocio.",
    image: "https://randomuser.me/api/portraits/women/65.jpg",
    country: "Colombia",
    language: "Spanish",
    rating: 5,
  },
  {
    id: 18,
    name: "Eduardo Hernández",
    company: "Soluciones Globales Tech",
    position: "Director de Tecnología",
    quote: "Dominiqk tiene una capacidad única para identificar oportunidades tecnológicas en mercados diversos. Su estrategia de implementación de IA nos ayudó a mejorar significativamente nuestra eficiencia operativa y experiencia del cliente.",
    image: "https://randomuser.me/api/portraits/men/70.jpg",
    country: "Argentina",
    language: "Spanish",
    rating: 5,
  },
  {
    id: 19,
    name: "Sofía Ramírez",
    company: "Consultora Digital Internacional",
    position: "Gerente de Proyectos",
    quote: "La visión multicultural de Dominiqk fue fundamental para el éxito de nuestros proyectos internacionales. Sus soluciones tecnológicas consideran aspectos culturales y sociales que otros consultores suelen pasar por alto.",
    image: "https://randomuser.me/api/portraits/women/72.jpg",
    country: "Peru",
    language: "Spanish",
    rating: 5,
  },
  {
    id: 20,
    name: "Miguel Torres",
    company: "Innovación Empresarial Madrid",
    position: "Director General",
    quote: "Dominiqk revolucionó nuestra estrategia de transformación digital con un enfoque adaptado a nuestras necesidades específicas. Su experiencia internacional y conocimiento de múltiples industrias aportaron un valor incalculable.",
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    country: "Spain",
    language: "Spanish",
    rating: 5,
  },
];

// Helper function to group testimonials by language
export const getTestimonialsByLanguage = () => {
  return testimonials.reduce((acc, testimonial) => {
    const { language } = testimonial;
    if (!acc[language]) {
      acc[language] = [];
    }
    acc[language].push(testimonial);
    return acc;
  }, {} as Record<string, typeof testimonials>);
};

// Get all available languages
export const getAvailableLanguages = () => {
  const testimonialsByLanguage = getTestimonialsByLanguage();
  return Object.keys(testimonialsByLanguage);
};
