// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rohwyheclmjmiuoksvuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvaHd5aGVjbG1qbWl1b2tzdnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDY5MTYsImV4cCI6MjA2Mzg4MjkxNn0._9_-gvma5JbNPA-0MxRHGdCJcl1WxvAFy0xaqtbWSJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);